<?php
// Register ACF fields and field groups.
if (function_exists("register_field_group")) {
    register_field_group(array(
        'id' => 'acf_product-guide',
        'title' => 'Product Guide',
        'fields' => array(
            array(
                'key' => 'field_50',
                'label' => 'Article',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_47',
                'label' => 'Article content',
                'name' => 'article_content',
                'type' => 'wysiwyg',
                'instructions' => 'If this is a standalone Product Guide, you can customize the content that appears before and after the Product Guide. For most applications, however, a Product Guide should be inserted into a regular post using a shortcode. You can find the shortcode for this Product Guide in the <a href="/wp-admin/edit.php?post_type=product-guide">Product Guide column view</a>.',
                'default_value' => '',
                'toolbar' => 'full',
                'media_upload' => 'yes',
                'the_content' => 'yes',
            ),
            array(
                'key' => 'field_54',
                'label' => 'Article content - after',
                'name' => 'article_content_after',
                'type' => 'wysiwyg',
                'instructions' => 'If this is a standalone Product Guide, you can customize the content that appears before and after the Product Guide. For most applications, however, a Product Guide should be inserted into a regular post using a shortcode. You can find the shortcode for this Product Guide in the <a href="/wp-admin/edit.php?post_type=product-guide">Product Guide column view</a>.',
                'default_value' => '',
                'toolbar' => 'full',
                'media_upload' => 'yes',
                'the_content' => 'yes',
            ),
            array(
                'key' => 'field_48',
                'label' => 'Questions',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_53',
                'label' => 'Question Group',
                'name' => 'question_group',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_32',
                        'label' => 'Question',
                        'name' => 'question',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_35',
                        'label' => 'Answers',
                        'name' => 'answers',
                        'type' => 'repeater',
                        'column_width' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_36',
                                'label' => 'answer title',
                                'name' => 'answer_title',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'formatting' => 'none',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_55',
                                'label' => 'Image',
                                'name' => 'answer_image',
                                'type' => 'image',
                                'column_width' => '',
                                'save_format' => 'url',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                            ),
                        ),
                        'row_min' => 0,
                        'row_limit' => '',
                        'layout' => 'table',
                        'button_label' => 'Add Row',
                    ),
                ),
                'row_min' => 0,
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Add Row',
            ),
            array(
                'key' => 'field_51',
                'label' => 'Device Qualities',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_52',
                'label' => 'The Results',
                'name' => 'result_qualities',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_64',
                        'label' => 'Device List',
                        'name' => 'device_list',
                        'type' => 'repeater',
                        'column_width' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_72',
                                'label' => 'Device Guid',
                                'name' => 'device_guid',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'formatting' => 'none',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_73',
                                'label' => 'Device',
                                'name' => 'device',
                                'type' => 'repeater',
                                'column_width' => '',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_81',
                                        'label' => 'Name',
                                        'name' => 'device_name',
                                        'type' => 'text',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'formatting' => 'none',
                                        'maxlength' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                    ),
                                    array(
                                        'key' => 'field_88',
                                        'label' => 'Include in',
                                        'name' => 'include_in',
                                        'type' => 'checkbox',
                                        'choices' => array(
                                            'guide' => 'Guide',
                                            'featured' => 'Featured',
                                        ),
                                        'column_width' => '',
                                        'default_value' => 'guide',
                                        'layout' => 'vertical',
                                    ),
                                    array(
                                        'key' => 'field_82',
                                        'label' => 'Price',
                                        'name' => 'device_price',
                                        'type' => 'number',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'min' => '',
                                        'max' => '',
                                        'step' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                    ),
                                    array(
                                        'key' => 'field_83',
                                        'label' => 'Auto Update',
                                        'name' => 'auto_update',
                                        'type' => 'select',
                                        'choices' => array(
                                            'auto' => 'Auto',
                                            'manual' => 'Manual',
                                        ),
                                        'column_width' => '',
                                        'default_value' => 'auto',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                    ),
                                ),
                                'row_min' => 1,
                                'row_limit' => 1,
                                'layout' => 'row',
                                'button_label' => 'Add Row',
                            ),
                            array(
                                'key' => 'field_74',
                                'label' => 'Device Description',
                                'name' => 'device_description',
                                'type' => 'textarea',
                                'column_width' => '',
                                'default_value' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                                'placeholder' => '',
                                'rows' => '',
                            ),
                            array(
                                'key' => 'field_78',
                                'label' => 'Images',
                                'name' => 'device_images',
                                'type' => 'repeater',
                                'column_width' => '',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_79',
                                        'label' => 'Device Image',
                                        'name' => 'device_image',
                                        'type' => 'image',
                                        'column_width' => '',
                                        'save_format' => 'id',
                                        'preview_size' => 'thumbnail',
                                        'library' => 'all',
                                    ),
                                    array(
                                        'key' => 'field_80',
                                        'label' => 'Review Image',
                                        'name' => 'review_image',
                                        'type' => 'image',
                                        'column_width' => '',
                                        'save_format' => 'id',
                                        'preview_size' => 'thumbnail',
                                        'library' => 'all',
                                    ),
                                ),
                                'row_min' => 1,
                                'row_limit' => 1,
                                'layout' => 'table',
                                'button_label' => 'Add Row',
                            ),
                            array(
                                'key' => 'field_64',
                                'label' => 'Device Legal',
                                'name' => 'device_legal',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'formatting' => 'none',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_65',
                                'label' => 'CTA URL',
                                'name' => 'device_cta_url',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'formatting' => 'none',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                        ),
                        'row_min' => 1,
                        'row_limit' => 1,
                        'layout' => 'row',
                        'button_label' => 'Add Row',
                    ),
                    array(
                        'key' => 'field_65',
                        'label' => 'The Questions',
                        'name' => 'device_qualities',
                        'type' => 'repeater',
                        'column_width' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_75',
                                'label' => '',
                                'name' => 'question_1',
                                'type' => 'checkbox',
                                'choices' => array(),
                                'column_width' => '',
                                'default_value' => '',
                                'layout' => 'vertical',
                            ),
                            array(
                                'key' => 'field_76',
                                'label' => '',
                                'name' => 'question_2',
                                'type' => 'checkbox',
                                'choices' => array(),
                                'column_width' => '',
                                'default_value' => '',
                                'layout' => 'vertical',
                            ),
                            array(
                                'key' => 'field_77',
                                'label' => '',
                                'name' => 'question_3',
                                'type' => 'checkbox',
                                'choices' => array(),
                                'column_width' => '',
                                'default_value' => '',
                                'layout' => 'vertical',
                            ),
                        ),
                        'row_min' => 1,
                        'row_limit' => 1,
                        'layout' => 'row',
                        'button_label' => 'Add Row',
                    ),
                ),
                'row_min' => 1,
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Add Device',
            ),
            array(
                'key' => 'field_49',
                'label' => 'PCM Feed Settings',
                'name' => '',
                'type' => 'tab',
            ),
            array(
                'key' => 'field_44',
                'label' => 'Feed URL',
                'name' => 'pcm_feed_url',
                'type' => 'text',
                'required' => 1,
                'default_value' => 'http://www.t-mobile.com/Services/v1/',
                'formatting' => 'none',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_45',
                'label' => 'Partner ID',
                'name' => 'pcm_partner_id',
                'type' => 'text',
                'required' => 1,
                'default_value' => 'glg-studio',
                'formatting' => 'none',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_46',
                'label' => 'Partner Key',
                'name' => 'pcm_partner_key',
                'type' => 'text',
                'required' => 1,
                'default_value' => 'studio',
                'formatting' => 'none',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'product-guide',
                    'order_no' => '0',
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array(
                0 => 'the_content',
                1 => 'excerpt',
                2 => 'custom_fields',
                3 => 'discussion',
                4 => 'comments',
                5 => 'revisions',
                6 => 'slug',
                7 => 'author',
                8 => 'format',
                9 => 'tags',
                10 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 1,
    ));
}
